// config/icons.ts
export const primeIcons = [
    { label: 'Home', value: 'pi pi-home' },
    { label: 'Database', value: 'pi pi-database' },
    { label: 'Box', value: 'pi pi-box' },
    { label: 'Users', value: 'pi pi-users' },
    { label: 'User', value: 'pi pi-user' },
    { label: 'Shopping Cart', value: 'pi pi-shopping-cart' },
    { label: 'Truck', value: 'pi pi-truck' },
    { label: 'Dollar', value: 'pi pi-dollar' },
    { label: 'Calculator', value: 'pi pi-calculator' },
    { label: 'Cog', value: 'pi pi-cog' },
    { label: 'Folder', value: 'pi pi-folder' },
    { label: 'List', value: 'pi pi-list' },
    { label: 'Chart Bar', value: 'pi pi-chart-bar' },
    { label: 'Chart Pie', value: 'pi pi-chart-pie' },
    { label: 'Chart Line', value: 'pi pi-chart-line' },
    { label: 'File', value: 'pi pi-file' },
    { label: 'File Edit', value: 'pi pi-file-edit' },
    { label: 'File Plus', value: 'pi pi-file-plus' },
    { label: 'Pen/Edit', value: 'pi pi-pencil' },
    { label: 'Trash', value: 'pi pi-trash' },
    { label: 'Plus', value: 'pi pi-plus' },
    { label: 'Minus', value: 'pi pi-minus' },
    { label: 'Times', value: 'pi pi-times' },
    { label: 'Check', value: 'pi pi-check' },
    { label: 'Check Circle', value: 'pi pi-check-circle' },
    { label: 'Exclamation', value: 'pi pi-exclamation-triangle' },
    { label: 'Info Circle', value: 'pi pi-info-circle' },
    { label: 'Lock', value: 'pi pi-lock' },
    { label: 'Shield', value: 'pi pi-shield' },
    { label: 'Key', value: 'pi pi-key' },
    { label: 'Search', value: 'pi pi-search' },
    { label: 'Filter', value: 'pi pi-filter' },
    { label: 'Refresh', value: 'pi pi-refresh' },
    { label: 'Calendar', value: 'pi pi-calendar' },
    { label: 'Clock', value: 'pi pi-clock' },
    { label: 'Star', value: 'pi pi-star' },
    { label: 'Star Fill', value: 'pi pi-star-fill' },
    { label: 'Heart', value: 'pi pi-heart' },
    { label: 'Thumbtack', value: 'pi pi-thumbtack' },
    { label: 'Tag', value: 'pi pi-tags' },
    { label: 'Book', value: 'pi pi-book' },
    { label: 'Print', value: 'pi pi-print' },
    { label: 'Download', value: 'pi pi-download' },
    { label: 'Upload', value: 'pi pi-upload' },
    { label: 'Sign Out', value: 'pi pi-sign-out' },
    { label: 'Sign In', value: 'pi pi-sign-in' },
    { label: 'Wallet', value: 'pi pi-wallet' },
    { label: 'Credit Card', value: 'pi pi-credit-card' },
    { label: 'Map Marker', value: 'pi pi-map-marker' },
    { label: 'Phone', value: 'pi pi-phone' },
    { label: 'Envelope', value: 'pi pi-envelope' },
    { label: 'Image', value: 'pi pi-image' },
    { label: 'Camera', value: 'pi pi-camera' },
    { label: 'Video', value: 'pi pi-video' },
    { label: 'Music', value: 'pi pi-music' },
    { label: 'Cloud', value: 'pi pi-cloud' },
    { label: 'Sun', value: 'pi pi-sun' },
    { label: 'Moon', value: 'pi pi-moon' },
    { label: 'Palette', value: 'pi pi-palette' },
    { label: 'Inbox', value: 'pi pi-inbox' },
    { label: 'Spinner', value: 'pi pi-spinner' },
    { label: 'Circle', value: 'pi pi-circle' },
    { label: 'Bars', value: 'pi pi-bars' },
    { label: 'Ellipsis H', value: 'pi pi-ellipsis-h' },
    { label: 'Ellipsis V', value: 'pi pi-ellipsis-v' },
    { label: 'Arrow Left', value: 'pi pi-arrow-left' },
    { label: 'Arrow Right', value: 'pi pi-arrow-right' },
    { label: 'Chevron Left', value: 'pi pi-chevron-left' },
    { label: 'Chevron Right', value: 'pi pi-chevron-right' },
    { label: 'Chevron Down', value: 'pi pi-chevron-down' },
    { label: 'Angle Double Left', value: 'pi pi-angle-double-left' },
    { label: 'Angle Double Right', value: 'pi pi-angle-double-right' },
]